version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    container_name: reporting-nginx
    image: nginx:1.21
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PHP Service
  php:
    container_name: reporting-php
    build: ./.docker/php
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    container_name: reporting-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql

# Volumes
volumes:
  mysqldata:
